### ISSUE TITLE
Update phpunit config to allow var_dump output

### ISSUE THREAD

**Issue by nathanielks** [humanmade/altis-dev-tools-command#10]
I was debugging a project's unit tests and found that phpunit was swallowing any output. Turns out we can configure phpunit to output this data without swallowing it by adding `beStrictAboutOutputDuringTests="false"` to the phpunit config:

https://github.com/humanmade/altis-dev-tools-command/blob/6316476125c696115afcc2e7181b9c6b1133f22c/inc/command/class-command.php#L96-L103

This allows me to use `var_dump()` inside tests without needing to `exit` at the end of it.

**Comment by rmccue** [comment]
Closing as this was just a could have.
