### ISSUE TITLE
composer dev-tools phpunit returns wp_die

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-dev-tools-command#4]
I upgraded Altis to 3.0.0-rc1 in order to get the built-in PHPUnit since I was unable to get PHPUnit working on 2.0.0. After upgrading (using the [upgrading to v3 documentation](https://github.com/humanmade/altis-documentation/blob/master/other-docs/guides/upgrading/v3.md)), and moving the tests into `/tests/` from `/.tests/`, running `composer dev-tools phpunit` gives me this:

```bash
$  composer dev-tools phpunit

wp_die called
Message : 
Title : 
```

This is the branch I am working with for 99co [altis-dec-setup](https://github.com/humanmade/99co/tree/altis-dec-setup)

**Comment by roborourke** [comment]
Hey @jazzsequence, I did some debugging and I've got that branch working now, all tests passing. I've updated the upgrade to link to the migration guide and updated the migration guide with details about defining the `SUNRISE` constant.

I've commented further in slack but the sake of searchability etc I'll paste my findings here too:

- `is_multisite()` needs to be undefined during install so I had to wrap the `define( 'SUNRISE', true )` line with a check for `WP_INITIAL_INSTALL` - that’s a new constant we added in v3
- there was a plugin adding roles on the `init` action which updates the options table - that action is run during WP CLI commands even before WP has been installed resulting in warnings so I tidied that up too
- The unit test classes needed to be named `class-test-*.php` , `test-*.php` or `*-test.php` to be automatically picked up
- Custom module loading is now MoreBetter™️ and can be done by adding to the `extra.altis.modules` property in `composer.json` using the `entrypoint` property, this ensures they’re only bootstrapped in a WP context
- I moved the relevant tests bootstrap code `.config/tests-bootstrap.php` - things like auto updates are now switched off by default and the `tests-uploads` directory switch is built in
