### ISSUE TITLE
Codespaces VM is does not have php-zip available which composer.json requires

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-dev-tools-command#42]
The Codespaces docker container generated from the `Dockerfile` does not have `php-zip` extension available. Though Altis `composer.json` requires it.

Trying to install it manually gives an error message indicating only php7.4 libs are avaialble.
 
Similarly adding the install to the Docker file gives the same result:
```
2022-07-29 14:48:11.760Z: #7 [3/5] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive      && apt-get -y install --no-install-recommends php-zip
2022-07-29 14:48:12.474Z: #7 0.747 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
...
2022-07-29 14:48:13.795Z: #7 2.100 Fetched 8749 kB in 1s (6367 kB/s)
2022-07-29 14:48:13.814Z: 
2022-07-29 14:48:13.831Z: #7 2.100 Reading package lists...
2022-07-29 14:48:14.189Z: 
2022-07-29 14:48:14.206Z: #7 2.610 Reading package lists...
2022-07-29 14:48:14.810Z: 
2022-07-29 14:48:14.828Z: #7 3.121 Building dependency tree...
2022-07-29 14:48:14.925Z: 
2022-07-29 14:48:15.040Z: #7 3.240 Reading state information...
2022-07-29 14:48:15.075Z: #7 3.260 Package php-zip is a virtual package provided by:
2022-07-29 14:48:15.111Z: 
2022-07-29 14:48:15.132Z: #7 3.260   php7.4-zip 7.4.30-1+deb11u1 [Not candidate version]
2022-07-29 14:48:15.163Z: #7 3.260   php7.4-zip 7.4.28-1+deb11u1 [Not candidate version]
2022-07-29 14:48:15.197Z: #7 3.260 
2022-07-29 14:48:15.229Z: #7 3.324 E: Package 'php-zip' has no installation candidate
```

**Comment by mikelittle** [comment]
## Workaround 
Note: Running `composer install --ignore-platform-req=ext-zip --ignore-platform-req=ext-zip` gets around the missing extension.

**Comment by kovshenin** [comment]
I don't think it's Altis that requires ext-zip, looking at the tree it looks like:

* altis/dev-tools requires codeception/module-webdriver
* codeception/module-webdriver requires php-webdriver/webdriver
* php-webdriver/webdriver requires ext-zip

Either way, .zip files the theme/plugin installer/updater in core and WP-CLI also use the zip extension I think, so I'm a bit puzzled on how you were able to install and activate a theme in your tests. I'm going to add a PR to add the zip extension to the devcontainer Dockerfile.

**Comment by rmccue** [comment]
Hrm, seems a pain to *require* ext-zip just for codeception, although I guess it's fine.

**Comment by kovshenin** [comment]
Doesn't make much of a difference for us I think, since in [our php container build](https://github.com/humanmade/docker-wordpress-php/blob/master/Dockerfile#L90) we already install the zip extension anyway. Might be a problem for somebody running Altis outside of Altis, Local Server or Codespaces.

**Comment by rmccue** [comment]
Yeah, would be better if it worked with the default/universal container in Codespaces (unless it does and our previous PHP one was more like a minimal one?)

**Comment by kovshenin** [comment]
I think it's just `composer install` that fails the extension check in the Codespaces container and complains. For the actual runtime it still runs our container through Local Server, which is I think why @mikelittle was able to install a .zip through the ignore-platform-req args.

**Comment by rmccue** [comment]
I'm wondering if `altis/dev-tools` could maybe have Codeception as a recommend instead of depend?

**Comment by kovshenin** [comment]
Hmm that's a good argument, if it's required it'll mean that Altis users will need the zip extension on their local development environments as well, without even using Codespaces. Perhaps we should move all the Codeception packages to recommended, and make sure they're installed when used with Codeception only. @shadyvb thoughts?

**Comment by shadyvb** [comment]
> so I'm a bit puzzled on how you were able to install and activate a theme in your tests

I might be missing something, but don't we run Codeception inside the container which has the zip extension ? vs `composer install` which runs on the local host. That's where the discrepancy come from if i'm not mistaken. 

Moving packages to recommended would be okay 👍  provided we update documentation properly, possibly also updating the `codecept` command to spit out steps to install the packages needed to run the tests, would also need to update CI config to install the packages as well.

**Comment by kovshenin** [comment]
Hmm, I think I might have confused Codeception with Codespaces in one or two sentences :( I don't think we should move Codeception to recommended/suggested packages since that would alter the way we setup CI for new projects, but also existing ones upgrading to v12.

I think we should go ahead and install the zip extension in the Codespaces "host container", the way their base Dockerfile [is authored](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/php/.devcontainer/base.Dockerfile) feels like the devcontainer is meant to be customized anyway.
