### ISSUE TITLE
PHP unit tests fail

### ISSUE THREAD

**Issue by stuartshields** [humanmade/altis-dev-tools-command#6]
@roborourke and @rmccue So let's see if I can explain this better in a ticket.

- When using dev-master of `local-server` trying to run `composer dev-tools phpunit` returns this error:
```
Could not read " vendor/phpunit.xml".
```

Now this happens both locally and when local-server is being run via TravisCI, so there is a bug somewhere.

However running: `composer server exec -- vendor/bin/phpunit -c vendor/phpunit.xml` works as it should.

For reference here is the `-c phpunit.xml` line:
https://github.com/humanmade/altis-dev-tools-command/blob/master/inc/command/class-command.php#L160

**Comment by roborourke** [comment]
Confirmed, looking into it.

**Comment by roborourke** [comment]
PR is up at #7
